import './globals.css';
import Navigation from '@/components/navigation';
import CustomMantineProvider from '@/components/provider';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className='flex flex-col h-screen mx-auto'>
				<CustomMantineProvider key={'custom-provider'}>
					<Navigation />
					{children}
				</CustomMantineProvider>
			</body>
		</html>
	);
}
