import './globals.css';
import Header from '@/components/header';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' data-theme='mytheme' className='mytheme'>
			<body className='flex flex-col h-screen mx-auto max-w-5xl'>
				<Header />
				{children}
			</body>
		</html>
	);
}
